AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: |
  Accounting - Sheets module

Parameters:
  SpreadsheetId:
    Type: String
  GoogleCredentialsFile:
    Type: String

Globals:
  Function:
    Timeout: 10
    Handler: app.lambdaHandler
    Runtime: nodejs20.x
    Architectures:
      - x86_64

Resources:
  TransactionWriter:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: transaction_writer/
      Environment:
        Variables:
          SPREADSHEET_ID: !Ref SpreadsheetId
          GOOGLE_APPLICATION_CREDENTIALS: !Ref GoogleCredentialsFile
      Events:
        TransactionEventRule:
          Type: EventBridgeRule
          Properties:
            Pattern:
              source:
                - custom.gtw.accountingApp
              detail-type:
                - transaction