AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: |
  Accounting - Sheets module

Parameters:
  SpreadsheetId:
    Type: String
  GCPProjectNumber:
    Type: String
  GCPProjectId:
    Type: String

Globals:
  Function:
    Timeout: 10
    Handler: app.lambdaHandler
    Runtime: nodejs20.x
    Architectures:
      - x86_64

Resources:
  TransactionWriter:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: transaction_writer/
      Environment:
        Variables:
          SPREADSHEET_ID: !Ref SpreadsheetId
          GOOGLE_AUDIENCE: !Sub "//iam.googleapis.com/projects/${GCPProjectNumber}/locations/global/workloadIdentityPools/aws-pool/providers/aws-provider"
          GOOGLE_SERVICE_ACCOUNT: !Sub "sheets-writer@${GCPProjectId}.iam.gserviceaccount.com"
      Policies:
        - Statement:
            - Effect: Allow
              Action: 
                - "sts:AssumeRoleWithWebIdentity"
              Resource: "*"
      Events:
        TransactionEventRule:
          Type: EventBridgeRule
          Properties:
            Pattern:
              source:
                - custom.gtw.accountingApp
              detail-type:
                - transaction