AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: |
  Accounting - Ebay module
Parameters:
  RestApiId:
    Type: String

Globals:
  Function:
    Timeout: 10
    Handler: app.lambdaHandler
    Runtime: nodejs20.x
    Architectures:
      - x86_64

Resources:
  OrderEnricher:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: order_enricher/
      Events:
        OrderTransactionEventRule:
          Type: EventBridgeRule
          Properties:
            Pattern:
              detail-type:
                - transaction
              detail:
                who:
                  - eBay
                description:
                  - prefix: eBay O*
    Connectors:
      OutgoingTopicConnector:
        Properties:
          Destination:
            Type: AWS::Events::EventBus
            Arn: !Sub arn:${AWS::Partition}:events:${AWS::Region}:${AWS::AccountId}:event-bus/default
          Permissions:
            - Write