# More information about the configuration file can be found here:
# https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/serverless-sam-cli-config.html
version = 0.1

[default]
[default.global.parameters]
stack_name = "accounting"

[default.build.parameters]
cached = true
parallel = true

[default.validate.parameters]
lint = true

[default.deploy.parameters]
capabilities = "CAPABILITY_IAM"
resolve_s3 = true
s3_prefix = "accounting"
region = "eu-west-2"
parameter_overrides = [
    "GoogleCredentialsFile=./google_credentials.json",
    "SpreadsheetId=\"1x_P7IH0Tp_7IvpAM5pDk_X3sRsZy7BBUljK40Q0JAZs\"",
    "StarlingPersonalPublicKey=\"MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEA1l50X6PjpAfGTKGw2qVSfZtC9Xc1piTAh0RdE30A3/zIu6h2UybNq3y5Z5thdsoZ2VwiRngIVhZk0x9g4uFMZRIwqDt5jZHQOA2TzAgXFhUMCd1M9hd23AyjVBMeuiQkDRnRTtwe1847t3+5PUrtsbR4RdhLKX/cJXxNF2ldDCpQRbx0czSJYfJGPP73Xh570gCaW6HRGztACM3sU/Olmr8AoFaaObxBwd4MFj3AjzgZfOBiF2YYFYXAXLdQ7s1kTqEVaR6bd/w2jniuMM51iyd7Ch3dYvv5tHVdNh+BKpUpMlZ9j64mtkgi8IRgK92rVsyNrDaBJiat8z2oF3YeHwIDAQAB\"",
    "StarlingBusinessPublicKey=\"MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAzCLwbvTLCWgX8Qn6syZl/i6+hPObhPbsVo7pXTgSzxqfNLI2xdU5uOKfsUUJLYBa2YfkU27K+WgRkPAlXfTCPC71VA8vdMW0QnOQYpavCQ3EejWeqdpUAZzKW2iL9wmaek64Wv/rvL22UmzrsKSXep/NXwJKPfK5QluKmNyseQWMghX9XzUA+OcBURW4DHNbg3EQpFKzzGRiQwTISQsD9RhCIfP/gMJE0gXCErf+APZs+SUMwTlyEEVyEUefr2kV8yQU0Hi/o62s0ZnTLB+NgyMpbU9+eNY9SomFOXTpUNpMV5g34Yohk4C7vgUL6EyprZBRnzYQMxmqoEvIE8DTKwIDAQAB\""
    ]
image_repositories = []

[default.package.parameters]
resolve_s3 = true

[default.sync.parameters]
watch = true

[default.local_start_api.parameters]
warm_containers = "EAGER"

[default.local_start_lambda.parameters]
warm_containers = "EAGER"

[default.local_invoke.parameters]
parameter_overrides = [
    "GoogleCredentialsFile=./google_credentials.json",
    "SpreadsheetId=1ma6kpdHG1FM0HACbBVA8S1b71jAOGMO0s1SpTDfJiF4",
    "StarlingPersonalPublicKey=\"MIGeMA0GCSqGSIb3DQEBAQUAA4GMADCBiAKBgH5uRK0zEWL5r1Njq7KaTMbzOAO9\n+vdWI1dt0Y2vN/ExslAcxETsZSwE2k5iGgsnBqfk6Ht54pZBoJ2s7NsAUbNdWu6V\nSYwBYBCr/9k2xY9cmOREIlyTjEL9OFjDc5N16v3Mwr+OdXfjqI+yNERYa0OcquVU\n8ccq1oAqlCYWMn//AgMBAAE=\"",
    "StarlingBusinessPublicKey=\"MIGeMA0GCSqGSIb3DQEBAQUAA4GMADCBiAKBgH5uRK0zEWL5r1Njq7KaTMbzOAO9\n+vdWI1dt0Y2vN/ExslAcxETsZSwE2k5iGgsnBqfk6Ht54pZBoJ2s7NsAUbNdWu6V\nSYwBYBCr/9k2xY9cmOREIlyTjEL9OFjDc5N16v3Mwr+OdXfjqI+yNERYa0OcquVU\n8ccq1oAqlCYWMn//AgMBAAEB\""
]
