AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: >
  sam_app
Parameters:
  SpreadsheetId:
    Type: String
  StarlingPersonalPublicKey:
    Type: String
  StarlingBusinessPublicKey:
    Type: String
  GoogleCredentialsFile:
    Type: String

Globals:
  Function:
    Timeout: 10
    Handler: app.lambdaHandler
    Runtime: nodejs20.x
    Architectures:
      - x86_64

Resources:
  DeliveryStatusLogger:
    Type: AWS::IAM::Role
    Properties:
      Policies:
        - PolicyName: DeliveryStatusLoggerPolicy
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action:
                  - logs:*
                Resource: "*"
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - sns.amazonaws.com
            Action:
              - sts:AssumeRole
  AccountingEntryTopic:
    Type: AWS::SNS::Topic
    Properties:
      DeliveryStatusLogging:
        - Protocol: sqs
          SuccessFeedbackSampleRate: "0"
          SuccessFeedbackRoleArn: !GetAtt DeliveryStatusLogger.Arn
          FailureFeedbackRoleArn: !GetAtt DeliveryStatusLogger.Arn
    Connectors:
      SheetsWriterQueueConnector:
        Properties:
          Destination:
            Id: SheetsWriterQueue
          Permissions:
            - Write
      EbayOrderEnricherQueueConnector:
        Properties:
          Destination:
            Id: EbayOrderEnricherQueue
          Permissions:
            - Write
      EbayPayoutEnricherQueueConnector:
        Properties:
          Destination:
            Id: EbayPayoutEnricherQueue
          Permissions:
            - Write
  EbayOrderEnricherQueue:
    Type: AWS::SQS::Queue
  EbayPayoutEnricherQueue:
    Type: AWS::SQS::Queue
  SheetsWriterQueue:
    Type: AWS::SQS::Queue
  SheetsWriterAccountingEntrySubscription:
    Type: AWS::SNS::Subscription
    Properties:
      Protocol: sqs
      TopicArn: !Ref AccountingEntryTopic
      Endpoint: !GetAtt SheetsWriterQueue.Arn
      RawMessageDelivery: true
      FilterPolicyScope: MessageAttributes
      FilterPolicy:
        {
          "eBayOrderId": [{ "exists": false }],
          "eBayPayoutId": [{ "exists": false }],
        }
  EbayOrderEnricherAccountingEntrySubscription:
    Type: AWS::SNS::Subscription
    Properties:
      Protocol: sqs
      TopicArn: !Ref AccountingEntryTopic
      Endpoint: !GetAtt EbayOrderEnricherQueue.Arn
      RawMessageDelivery: true
      FilterPolicyScope: MessageAttributes
      FilterPolicy: { "eBayOrderId": [{ "exists": true }] }
  EbayPayoutEnricherAccountingEntrySubscription:
    Type: AWS::SNS::Subscription
    Properties:
      Protocol: sqs
      TopicArn: !Ref AccountingEntryTopic
      Endpoint: !GetAtt EbayPayoutEnricherQueue.Arn
      RawMessageDelivery: true
      FilterPolicyScope: MessageAttributes
      FilterPolicy: { "eBayPayoutId": [{ "exists": true }] }
  StarlingVerifiedFeedItemQueue:
    Type: AWS::SQS::Queue
  StarlingPersonalFeedItemWebhook:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: starling_feed_item_webhook/
      Environment:
        Variables:
          PUBLIC_KEY: !Ref StarlingPersonalPublicKey
          QUEUE_URL: !GetAtt StarlingVerifiedFeedItemQueue.QueueUrl
      Events:
        StarlingFeedItem:
          Type: Api
          Properties:
            Path: /starling/feed-item
            Method: post
    Connectors:
      OutgoingQueueConnector:
        Properties:
          Destination:
            Id: StarlingVerifiedFeedItemQueue
          Permissions:
            - Write
  StarlingBusinessFeedItemWebhook:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: starling_feed_item_webhook/
      Environment:
        Variables:
          PUBLIC_KEY: !Ref StarlingBusinessPublicKey
          QUEUE_URL: !GetAtt StarlingVerifiedFeedItemQueue.QueueUrl
      Events:
        StarlingFeedItem:
          Type: Api
          Properties:
            Path: /starling/business/feed-item
            Method: post
    Connectors:
      OutgoingQueueConnector:
        Properties:
          Destination:
            Id: StarlingVerifiedFeedItemQueue
          Permissions:
            - Write
  StarlingFeedItemToTransaction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: starling_feed_item_to_transaction/
      Environment:
        Variables:
          TOPIC_ARN: !GetAtt AccountingEntryTopic.TopicArn
      Events:
        VerifiedStarlingFeedItem:
          Type: SQS
          Properties:
            Queue: !GetAtt StarlingVerifiedFeedItemQueue.Arn
    Connectors:
      OutgoingTopicConnector:
        Properties:
          Destination:
            Id: AccountingEntryTopic
          Permissions:
            - Write
      IncomingQueueConnector:
        Properties:
          Destination:
            Id: StarlingVerifiedFeedItemQueue
          Permissions:
            - Read
  StarlingEbayOrderEnricher:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ebay_order_enricher/
      Environment:
        Variables:
          QUEUE_URL: !GetAtt SheetsWriterQueue.QueueUrl
      Events:
        AccountsEntry:
          Type: SQS
          Properties:
            Queue: !GetAtt EbayOrderEnricherQueue.Arn
    Connectors:
      IncomingQueueConnector:
        Properties:
          Destination:
            Id: EbayOrderEnricherQueue
          Permissions:
            - Read
      OutgoingQueueConnector:
        Properties:
          Destination:
            Id: SheetsWriterQueue
          Permissions:
            - Write
  StarlingEbayPayoutEnricher:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ebay_payout_enricher/
      Environment:
        Variables:
          QUEUE_URL: !GetAtt SheetsWriterQueue.QueueUrl
      Events:
        AccountsEntry:
          Type: SQS
          Properties:
            Queue: !GetAtt EbayPayoutEnricherQueue.Arn
    Connectors:
      IncomingQueueConnector:
        Properties:
          Destination:
            Id: EbayPayoutEnricherQueue
          Permissions:
            - Read
      OutgoingQueueConnector:
        Properties:
          Destination:
            Id: SheetsWriterQueue
          Permissions:
            - Write
  SheetsWriter:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: sheets_writer/
      Environment:
        Variables:
          SPREADSHEET_ID: !Ref SpreadsheetId
          GOOGLE_APPLICATION_CREDENTIALS: !Ref GoogleCredentialsFile
      Events:
        AccountsEntry:
          Type: SQS
          Properties:
            Queue: !GetAtt SheetsWriterQueue.Arn
    Connectors:
      IncomingQueueConnector:
        Properties:
          Destination:
            Id: SheetsWriterQueue
          Permissions:
            - Read
