AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: |
  sam_app
Parameters:
  StarlingPublicKey:
    Type: String
  SpreadsheetId:
    Type: String
  GoogleCredentialsFile:
    Type: String

Globals:
  Function:
    Timeout: 10
    Handler: app.lambdaHandler
    Runtime: nodejs20.x
    Architectures:
      - x86_64

Resources:

  EbayModule:
    Type: AWS::Serverless::Application
    Properties:
      Location: ebay/template.yaml

  StarlingModule:
    Type: AWS::Serverless::Application
    Properties:
      Location: starling/template.yaml
      Parameters:
        StarlingPublicKey: !Ref StarlingPublicKey

  SheetsModule:
    Type: AWS::Serverless::Application
    Properties:
      Location: sheets/template.yaml
      Parameters:
        SpreadsheetId: !Ref SpreadsheetId
        GoogleCredentialsFile: !Ref GoogleCredentialsFile