AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: >
  sam_app
Parameters:
  SpreadsheetId:
    Type: String
  StarlingPersonalPublicKey:
    Type: String
  StarlingBusinessPublicKey:
    Type: String
  GoogleCredentialsFile:
    Type: String

Globals:
  Function:
    Timeout: 10
    Handler: app.lambdaHandler
    Runtime: nodejs20.x
    Architectures:
      - x86_64

Resources:
  EventSplitter:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: event_splitter/
      Events:
        AccountingEvents:
          Type: EventBridgeRule
          Properties:
            Pattern:
              source:
                - "lambda"
              detail-type:
                - "Lambda Function Invocation Result - Success"
    Connectors:
      OutgoingTopicConnector:
        Properties:
          Destination:
            Type: AWS::Events::EventBus
            Arn: !Sub arn:${AWS::Partition}:events:${AWS::Region}:${AWS::AccountId}:event-bus/default
          Permissions:
            - Write

  StarlingBusinessFeedItemWebhook:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: starling_feed_item_webhook/
      Environment:
        Variables:
          PUBLIC_KEY: !Ref StarlingBusinessPublicKey
      Events:
        StarlingFeedItem:
          Type: Api
          Properties:
            Path: /starling/business/feed-item
            Method: post
    Connectors:
      OutgoingTopicConnector:
        Properties:
          Destination:
            Type: AWS::Events::EventBus
            Arn: !Sub arn:${AWS::Partition}:events:${AWS::Region}:${AWS::AccountId}:event-bus/default
          Permissions:
            - Write

  StarlingFeedItemToTransaction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: starling_feed_item_to_transaction/
      Events:
        VerifiedStarlingFeedItemEventRule:
          Type: EventBridgeRule
          Properties:
            Pattern:
              source:
                - "custom.gtw.accountingApp"
              detail-type:
                - "starling-verified-feeditem"
      EventInvokeConfig:
        DestinationConfig:
          OnSuccess:
            Type: EventBridge
            Destination: !Sub arn:${AWS::Partition}:events:${AWS::Region}:${AWS::AccountId}:event-bus/default

  SheetsWriter:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: sheets_writer/
      Environment:
        Variables:
          SPREADSHEET_ID: !Ref SpreadsheetId
          GOOGLE_APPLICATION_CREDENTIALS: !Ref GoogleCredentialsFile
      Events:
        NewTransactionEventRule:
          Type: EventBridgeRule
          Properties:
            Pattern:
              detail-type:
                - transaction
              detail:
                MessageAttributes:
                  eBayOrderId:
                    - { "exists": false }
                  eBayPayoutId:
                    - { "exists": false }

  StarlingEbayOrderEnricher:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ebay_order_enricher/
      Events:
        NewEbayOrderTransactionEventRule:
          Type: EventBridgeRule
          Properties:
            Pattern:
              detail-type:
                - transaction
              detail:
                MessageAttributes:
                  eBayOrderId:
                    - { "exists": true }
      EventInvokeConfig:
        DestinationConfig:
          OnSuccess:
            Type: EventBridge
            Destination: !Sub arn:${AWS::Partition}:events:${AWS::Region}:${AWS::AccountId}:event-bus/default

  StarlingEbayPayoutEnricher:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ebay_payout_enricher/
      Events:
        NewEbayPayoutTransactionEventRule:
          Type: EventBridgeRule
          Properties:
            Pattern:
              detail-type:
                - transaction
              detail:
                MessageAttributes:
                  eBayPayoutId:
                    - { "exists": true }
      EventInvokeConfig:
        DestinationConfig:
          OnSuccess:
            Type: EventBridge
            Destination: !Sub arn:${AWS::Partition}:events:${AWS::Region}:${AWS::AccountId}:event-bus/default
