name: Deploy SAM Application

on:
  push:
    branches: [ main ]
    paths:
      - 'sam_app/**'
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  deploy-sam:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
          aws-region: eu-west-2

      - name: Setup SAM CLI
        uses: aws-actions/setup-sam@v2

      - name: Create personal.json
        run: |
          echo '${{ secrets.PERSONAL_DATA }}' > sam_app/starling/feed_item_to_transaction/personal.json

      - name: Create ebay-auth.json files
        run: |
          for dir in sam_app/ebay/order_enricher sam_app/ebay/token_gen sam_app/ebay/transaction_fetcher sam_app/ebay/non_sale_charge_to_transaction sam_app/ebay/shipping_label_to_transaction sam_app/ebay/sale_to_transaction sam_app/ebay/refund_to_transaction
          do
            echo '${{ secrets.EBAY_AUTH }}' > $dir/ebay-auth.json
          done

      - name: Build SAM application
        run: |
          cd sam_app
          sam build --parallel

      - name: Deploy SAM application
        run: |
          cd sam_app
          sam deploy --no-confirm-changeset --no-fail-on-empty-changeset 